#!/usr/bin/env bash
#a script it install Nginx and configure quering Nginx at its root / with GET request to return a page that contains the string "Hello World!"

sudo apt-get update
sudo apt-get install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
