#!/usr/bin/env bash
#install and configure the Ngnix web server

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	location / {
		try_files \$uri \$uri/ =404;
	}
}"

sudo bash -c "echo -e '$SERVER_CONFIG' | sudo tee /etc/nginx/sites-enabled/default"

sudo service nginx restart
