#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header:
#	name of the custom HTTP header is X-Served-By
#	value of the custom HTTP header is the hostname of the server Nginx is running on

new_string="http {\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s|http {|$new_string|" /etc/nginx/nginx.conf
sudo service nginx restart
