#!/usr/bin/env bash
#Configure Nginx so that its HTTP response contains a custom header:
#	name of the custom HTTP header is X-Served-By
#	value of the custom HTTP header is the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html

SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
        error_page 404 /404.html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	location / {
		try_files \$uri \$uri/ =404;
	}
}"

sudo bash -c "echo -e '$SERVER_CONFIG' | sudo tee /etc/nginx/sites-enabled/default"

new_string="http {\n\tadd_header X-Served-By \$hostname;"
sudo sed -i "s|http {|$new_string|" /etc/nginx/nginx.conf

sudo service nginx restart
