#!/usr/bin/env bash
#install and configure HAproxy on lb-01 server

sudo apt-get update
sudo apt-get -y install haproxy

new="\
backend backend_servers\n\
\tbalance roundrobin\n\
\tserver web-01 35.174.209.16:80 check\n\
\tserver web-02 35.153.226.72:80 check\n\
frontend http-in\n\
\tbind *:80\n\
\tdefault_backend backend_servers"

sudo sed -i -e "$ a $new" /etc/haproxy/haproxy.cfg

sudo service haproxy restart
