#!/usr/bin/env bash
#script that generates a MySQL dump and creates a compressed archive out of it

mysqldump -u root -p"$1" --databases tyrell_corp > backup.sql
tar -czvf "$(date +'%d-%m-%y').tar.gz" backup.sql
