#!/usr/bin/env bash
#configure ngnix server to listen on port 80 after installation

link="/etc/nginx/sites-enabled/default"
target="/etc/nginx/sites-available/default"
sudo rm $link
sudo ln -s $target $link
sudo service nginx restart
