#!/usr/bin/env bash
#configure ngnix server to listen on port 80 after installation

link="/etc/nginx/sites-enabled/default"
target="/etc/nginx/sites-available/default"
if [ -e "$link" ] && [ -L "$link" ]
then
        sudo rm $link
        sudo ln -s $target $link
else
        sudo ln -s $target $link
fi
sudo service nginx restart
