#!/usr/bin/env bash
# script that creates pid file for the process execute different command based
#+the signal it recievs

echo "$$" > /var/run/myscript.pid

handler(){
	rm /var/run/myscript.pid
	echo "I hate the kill command"
	exit
}

trap handler SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"; exit' SIGINT

while true
do
	echo "To infinity and beyond"
done
