#!/usr/bin/env bash
#displays the numbers from 1 to 100 and prints
#+FizzBuzz when the number is mutiple of 3 and 5
#+Fizz when the number is multiple of 3
#+Buzz when the number is multiple of 5
#+otherwise display the number

i=1

while [ $i -le 100 ]
do
	if [[ $((i % 3)) == 0 && $((i % 5)) == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $((i % 3)) == 0 ]]
	then
		echo "Fizz"
	elif [[ $((i % 5)) -eq 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
	i=$((i+1))
done

