#!/usr/bin/env bash
# script loop from 1 to 10 displaying "bad luck" for 4th iteration
#+ or "good luck" for 8th iteration otherwise "Best School"

i=1

while [ $i -le "10" ]
do
	if [ $i -eq "4" ]
	then
		echo "bad luck"
	elif [ $i -eq "8" ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
