#!/usr/bin/env bash
# a loop display numbers from 1 to 20 and "bad luck from china" for 4t itr
#+ "bad luck from japan" for 9th itr and "bad luck from italy" for 17th itr

i=1

while [ $i -le 20 ]
do
	case $i in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	i=$((i+1))
done
