#!/usr/bin/env bash
# this script gives information sbout the "school" file

file="school"

if [ -e $file ]
then
	echo "school file exists"
	if [ ! -s $file ]
	then
		echo "school file is empty"
		if [ -f $file ]
		then
			echo "school is a regular file"
		fi
	elif [ -s $file ]
	then
		echo "school file is not empty"
		if [ -f $file ]
		then
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
