#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user
#requirements:
#	nginx must be running as nginx user
#	nginx must be listening on all active IPs on port 8080
#	You cannot use apt-get remove

chmod 644  /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
pkill -f apache2
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
service nginx restart
