#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user
chmod 644  /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
netstat -lpn | grep :8080 | awk '{print $7}' | cut -d '/' -f 2 | xargs pkill -f
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
service nginx restart
