#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user
chmod 644  /etc/nginx/nginx.conf
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
pkill -f apache2
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
su nginx -c "service nginx restart"
